import Foundation

public enum NativeConsequenceCatalog {
    public static let semanticMemoryLimit = 400

    public static let factRecords: [NativeFactRecord] = [
        NativeFactRecord(countryCodes: ["GLOBAL"], detail: "The opening economy is still absorbing the 2008-2009 financial shock, with fiscal stimulus unwinding unevenly.", id: "GLOBAL_2010_POST_CRISIS_RECOVERY", startDate: "2010-01-01", tags: ["budget", "growth", "market", "fiscal"], title: "Post-crisis recovery"),
        NativeFactRecord(countryCodes: ["GLOBAL"], detail: "Energy import exposure matters for inflation, trade balance, and public confidence in infrastructure plans.", id: "GLOBAL_2010_ENERGY_EXPOSURE", startDate: "2010-01-01", tags: ["energy", "infrastructure", "inflation"], title: "Energy exposure"),
        NativeFactRecord(countryCodes: ["GLOBAL"], detail: "Public security capacity affects institutional trust, budget strain, service delivery, and the chance that local unrest becomes territorial control.", id: "GLOBAL_2010_PUBLIC_SECURITY_CAPACITY", startDate: "2010-01-01", tags: ["security", "public order", "insurgency", "rebel", "stability"], title: "Public security capacity"),
        NativeFactRecord(countryCodes: ["GLOBAL"], detail: "Border pressure and unresolved occupations can damage trade corridors even when no capital region changes hands.", id: "GLOBAL_2010_BORDER_PRESSURE", startDate: "2010-01-01", tags: ["border", "occupation", "conventional", "corridor", "trade"], title: "Border pressure"),
        NativeFactRecord(countryCodes: ["USA"], detail: "The United States starts with high deficits, high unemployment, and exceptional reserve-currency financing capacity.", id: "USA_2010_DEFICIT_RECOVERY", startDate: "2010-01-01", tags: ["budget", "debt", "employment"], title: "US deficit recovery"),
        NativeFactRecord(countryCodes: ["CHN"], detail: "China enters 2010 with strong growth, high investment, trade surplus, and rising inflation watchpoints.", id: "CHN_2010_STIMULUS_GROWTH", startDate: "2010-01-01", tags: ["growth", "trade", "inflation"], title: "China stimulus growth"),
        NativeFactRecord(countryCodes: ["BRA"], detail: "Brazil starts with strong growth, commodity leverage, manageable debt, and inflation pressure from demand.", id: "BRA_2010_COMMODITY_EXPANSION", startDate: "2010-01-01", tags: ["commodity", "energy", "budget", "growth"], title: "Brazil commodity expansion"),
        NativeFactRecord(countryCodes: ["DEU", "FRA", "GBR"], detail: "European economies face Eurozone debt stress, bank repair, and tighter fiscal politics.", id: "EUROPE_2010_DEBT_STRESS", startDate: "2010-01-01", tags: ["budget", "debt", "market"], title: "European debt stress"),
        NativeFactRecord(countryCodes: ["JPN"], detail: "Japan starts with deflation pressure, heavy public debt, advanced industry, and high energy import dependence.", id: "JPN_2010_DEFLATION_DEBT", startDate: "2010-01-01", tags: ["debt", "energy", "industry"], title: "Japan deflation and debt"),
        NativeFactRecord(countryCodes: ["IND"], detail: "India starts with fast growth, infrastructure bottlenecks, inflation pressure, and rising services capacity.", id: "IND_2010_GROWTH_INFLATION", startDate: "2010-01-01", tags: ["growth", "inflation", "infrastructure"], title: "India growth and inflation")
    ]

    public static let consequenceRules: [NativeConsequenceRule] = [
        NativeConsequenceRule(budgetBalanceDelta: -0.18, debtDelta: 0.28, description: "Fiscal buffers reduce short-run risk but widen the deficit until revenue or cuts offset the commitment.", fiscalSpaceDelta: 3, growthDelta: 0.04, id: "fiscal-buffer", inflationDelta: 0.02, keywords: ["buffer", "reserve", "bond", "fiscal"], summary: "Budget buffer: safer services, weaker near-term surplus.", tradeBalanceDelta: 0.00, track: .economicResilience),
        NativeConsequenceRule(budgetBalanceDelta: -0.25, debtDelta: 0.32, description: "Infrastructure spending raises capacity and growth, with near-term deficit pressure and modest import leakage.", fiscalSpaceDelta: 4, growthDelta: 0.16, id: "infrastructure-resilience", inflationDelta: 0.04, keywords: ["grid", "energy", "infrastructure", "transport", "port", "rail"], summary: "Infrastructure: higher growth capacity with upfront fiscal cost.", tradeBalanceDelta: -0.04, track: .economicResilience),
        NativeConsequenceRule(budgetBalanceDelta: -0.08, debtDelta: 0.08, description: "Administrative delivery improves confidence without a large fiscal impulse.", fiscalSpaceDelta: 2, growthDelta: 0.05, id: "service-delivery", inflationDelta: -0.01, keywords: ["service", "education", "audit", "agency", "administrative"], summary: "Service delivery: stability and confidence gains at low cost.", tradeBalanceDelta: 0.00, track: .internalStability),
        NativeConsequenceRule(budgetBalanceDelta: 0.04, debtDelta: -0.05, description: "Trade facilitation can improve receipts and market confidence if logistics capacity keeps up.", fiscalSpaceDelta: 3, growthDelta: 0.10, id: "trade-diplomacy", inflationDelta: -0.02, keywords: ["trade", "customs", "export", "corridor", "diplomacy", "agreement"], summary: "Trade diplomacy: stronger external balance and confidence.", tradeBalanceDelta: 0.16, track: .diplomaticLeverage),
        NativeConsequenceRule(budgetBalanceDelta: 0.02, debtDelta: -0.02, description: "Credible market signaling improves financing conditions but has limited direct real-economy impact.", fiscalSpaceDelta: 2, growthDelta: 0.04, id: "market-confidence", inflationDelta: -0.01, keywords: ["market", "confidence", "transparency", "publish"], summary: "Market confidence: cheaper financing and marginal growth support.", tradeBalanceDelta: 0.03, track: .marketConfidence),
        NativeConsequenceRule(budgetBalanceDelta: -0.12, debtDelta: 0.16, description: "External shocks stress public finances and trade while forcing near-term mitigation.", fiscalSpaceDelta: -4, growthDelta: -0.12, id: "external-shock", inflationDelta: 0.10, keywords: ["shock", "volatility", "disruption", "price"], summary: "External shock: weaker growth and fiscal pressure.", tradeBalanceDelta: -0.10, track: .worldTension),
        NativeConsequenceRule(budgetBalanceDelta: -0.05, debtDelta: 0.06, description: "Default civic programs create modest fiscal cost and modest delivery upside.", fiscalSpaceDelta: 1, growthDelta: 0.03, id: "default-civic", inflationDelta: 0.00, keywords: [], summary: "Civic action: small cost, small institutional gain.", tradeBalanceDelta: 0.00, track: .internalStability),
        NativeConsequenceRule(budgetBalanceDelta: -0.05, debtDelta: 0.06, description: "Public security programs reduce insurgency pressure but require sustained local legitimacy and budget room.", fiscalSpaceDelta: -1, growthDelta: 0.02, id: "public-security", inflationDelta: 0.01, keywords: ["security", "public safety", "public order", "policing", "seguranca", "segurança", "stabilization"], summary: "Public security: lower rebel pressure with budget cost.", tradeBalanceDelta: 0.00, track: .internalStability),
        NativeConsequenceRule(budgetBalanceDelta: -0.18, debtDelta: 0.22, description: "Insurgency containment protects service corridors but drags growth when local control remains contested.", fiscalSpaceDelta: -2, growthDelta: -0.03, id: "insurgency-containment", inflationDelta: 0.03, keywords: ["insurgency", "guerrilla", "rebel", "occupation", "border"], summary: "Insurgency containment: stabilizes control while slowing delivery.", tradeBalanceDelta: -0.02, track: .internalStability),
        NativeConsequenceRule(budgetBalanceDelta: -0.04, debtDelta: 0.08, description: "Macro demand remains fragile and can drift against the player if no credible fiscal path exists.", fiscalSpaceDelta: -1, growthDelta: -0.02, id: "macro-demand", inflationDelta: 0.03, keywords: [], summary: "Macro demand: fragile recovery pressure.", tradeBalanceDelta: -0.02, track: .economicResilience),
        NativeConsequenceRule(budgetBalanceDelta: -0.10, debtDelta: 0.12, description: "Recurring commitments can slowly erode budget space even without a headline shock.", fiscalSpaceDelta: -2, growthDelta: 0.00, id: "fiscal-drift", inflationDelta: 0.01, keywords: [], summary: "Fiscal drift: budget space narrows.", tradeBalanceDelta: 0.00, track: .economicResilience)
    ]

    public static let rulesByID = Dictionary(uniqueKeysWithValues: consequenceRules.map { ($0.id, $0) })
}
